const{_electron:electron}=require('@playwright/test'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const env={...process.env,DEXTERITY_TEST:'1'};delete env.ELECTRON_RUN_AS_NODE;const desktop=await electron.launch({...(process.env.DEXTERITY_PACKAGED?{executablePath:path.resolve('release-v1.7/win-unpacked/Dexterity.exe')}:{}),args:process.env.DEXTERITY_PACKAGED?[]:['.'],env});try{
 await desktop.firstWindow();let page;for(let i=0;i<100;i++){page=desktop.windows().find(p=>p.url().endsWith('/index.html'));if(page)break;await new Promise(r=>setTimeout(r,100));}await page.waitForFunction(()=>typeof prefs!=='undefined'&&prefs);const coach=desktop.windows().find(p=>p.url().endsWith('/coach.html'));const errors=[];coach.on('pageerror',e=>errors.push(e.message));
 await page.evaluate(async()=>{prefs=await api.saveSettings({...prefs,voice:false,routerKey:'fixture'});syncSettings();});
 await desktop.evaluate(()=>{globalThis.lessons=[];globalThis.fetch=async(url,o)=>{const input=JSON.parse(JSON.parse(o.body).messages[1].content[0].text);globalThis.lessons.push(input);return{ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:JSON.stringify({answer:'Click the Full name field. This is where you enter your name.',status:'done',target:{x:.3,y:.15,label:'Full name'},action:{type:'none',targetId:'',value:''}})}}]})};};});
 await page.locator('#task-demo').click();await page.waitForFunction(()=>document.getElementById('task-window').value!=='');await page.locator('[name="task-mode"][value="teach"]').check();await page.locator('#task-goal').fill('Teach me how to use this form.');await page.locator('#task-send').click();await coach.getByText('Click the Full name field. This is where you enter your name.',{exact:true}).waitFor();await page.waitForFunction(()=>!taskRunning,null,{polling:100});await coach.locator('#point').click();
 const visible=await desktop.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().filter(w=>w.isVisible()).map(w=>w.webContents.getURL()));assert.ok(visible.some(u=>u.endsWith('/coach.html')));assert.ok(visible.some(u=>u.endsWith('/pointer.html')));assert.ok(!visible.some(u=>u.endsWith('/index.html')));assert.equal(await coach.locator('#notice').innerText(),'');
 await coach.screenshot({path:'test-results/cursor-lesson.png'});await desktop.windows().find(p=>p.url().endsWith('/orb.html')).screenshot({path:'test-results/cursor-buddy.png'});await desktop.windows().find(p=>p.url().endsWith('/pointer.html')).screenshot({path:'test-results/cursor-pointer.png'});await coach.locator('#next').click();await page.waitForFunction(()=>!taskRunning,null,{polling:100});await coach.locator('#point').waitFor({state:'visible'});const lessons=await desktop.evaluate(()=>globalThis.lessons);assert.equal(lessons.length,2);assert.match(lessons[1].goal,/Teach me how to use this form/);assert.equal(lessons[1].mode,'teach');assert.deepEqual(errors,[]);console.log('PASS: floating lesson, click-through pointer, dashboard stays hidden, next-step recapture retains original lesson goal.');
}finally{await desktop.close();}})().catch(e=>{console.error(e);process.exit(1);});
